#!/bin/sh

exec chpst -U nobody:nogroup /bin/prometheus -config.file /mnt/mesos/sandbox/prometheus.yml \
  -storage.local.path /prometheus \
  -web.console.libraries /etc/prometheus/console_libraries \
  -web.console.templates /etc/prometheus/consoles \
  -alertmanager.url http://localhost:9093
